### ISSUE TITLE
Need support for LSI Fury Adapters

### ISSUE THREAD

**Issue by gdamore** [gdamore/illumos-core#164]
Newer HBAs with the MegaRaid Fury chip (PCI 0x1000,0x5f) are appearing now -- for example the Dell Perc H330 uses this controller.  Apparently it behaves the same as the Invader part that we already have support for -- at least according to my read of the FreeBSD driver supporting the same chips.

Mostly this probably means adding the vendor/device id recognition.  The way the current driver does this is ugly, btw.

**Comment by gdamore** [comment]
I have code for this, but testing pending.

**Comment by jontesehlin** [comment]
Have tested your code on my Dell R630 with an Dell Perc H330 controller in HBA mode.

Getting the following error for every drive that's connected to the controller on boot:
Warning: /pci@0,0/pci8086,2f04@2/pci1028,1f44@0/sd*,1 (sd*):
Command failed to complete...Device is gone
(Where's * is disk number)

Those errors are followed up by:
svc.start[8]: svc:/system/filesystem/smartdc:default: Method "/lib/svc/method/fs-joyent" failed with exit status 95.
svc.start[8]: svc:/system/filesystem/smartdc:default failed fatally: transitioned to maintenacnce (see 'svcs -xv' for details)
..............

My guess is that the later output is due to the zones zpool isn't mountable, as the discs' are "disconnected". If I boot into recovery mode I can mount the zpool. 

Note: If i run "format" I do receive:
Warning: /pci@0,0/pci8086,2f04@2/pci1028,1f44@0/sd*,1 (sd*): .........
for all drives. But this only occurs the first time i run "format".

This test was done with a SmartOS build done by irc user Nahamu. 
I'm currently building the current SmartOS and will test it out there too.

**Comment by gdamore** [comment]
I think there were some other changes that were made to the driver that need to be merged with mine.
